version: "3.9"
services:
  web:
    environment: 
      - CHOKIDAR_USERPOLLING=true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:app

    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Sapiencia123"
      ACCEPT_EULA: "Y"